### ISSUE TITLE
predictSeason?

### ISSUE THREAD

**Issue by jmoneill** [telliott27/rupaulsdragrace#7]
What does this cell in the Jupyter Notebook have to do with predicting the All-Stars stuff? Looks like in the AS3 one you did it with season 9, should I be doing it with season 10? Or is it not relevant?

`predictSeason(9,nn2_model,queens,True)`

**Comment by telliott27** [comment]
That's left over from the notebook predicting Drag Race non-AS seasons. You don't need that at all to predict all stars.

**Comment by jmoneill** [comment]
"Thank you." - Tatianna
